# -*- coding: utf-8 -*-
"""Reddit_Data_Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G2fTRanUJ5coJQWTu7CjXaKl4Y9xM6b5
"""

pip install praw

import praw
import pandas as pd

# Set up Reddit API client
reddit = praw.Reddit(
    client_id='tXYTFzHIczyP-J7uJ0nAjw',
    client_secret='CybX1LgBa_6fEUBLRI8FeL30WYLT6g',
    user_agent='DSSMA'
)

# Search keyword and limit
keyword = "zudio"
limit = 1000

# Search across all subreddits for the keyword
posts = []

for post in reddit.subreddit("all").search(keyword, limit=limit, sort='relevance'):
    posts.append({
        'id': post.id,
        'title': post.title,
        'content': post.selftext if post.selftext else '[No text content]',
        'score': post.score,
        'url': post.url,
        'num_comments': post.num_comments,
        'created_utc': post.created_utc
    })

# Convert to DataFrame and export
df = pd.DataFrame(posts)
df.to_csv(f"{keyword}_posts.csv", index=False)

print(f"✅ Saved {len(df)} posts matching keyword '{keyword}'")

import pandas as pd

df = pd.read_csv('/content/zudio_posts.csv')

df['content']

df.tail()

