version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PRAW_CLIENT_ID=${PRAW_CLIENT_ID}
      - PRAW_CLIENT_SECRET=${PRAW_CLIENT_SECRET}
      - PRAW_USER_AGENT=${PRAW_USER_AGENT:-ds-lab-app}
    volumes:
      - ./models:/app/models
      - ./prompt:/app/prompt
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PRAW_CLIENT_ID=${PRAW_CLIENT_ID}
      - PRAW_CLIENT_SECRET=${PRAW_CLIENT_SECRET}
      - PRAW_USER_AGENT=${PRAW_USER_AGENT:-ds-lab-app}
    volumes:
      - ./models:/app/models
      - ./prompt:/app/prompt
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - streamlit
    profiles:
      - production
